M48
; DRILL file {KiCad 6.0.0} date sam. 17 sept. 2022 11:35:33
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-17T11:35:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
%
G90
G05
T1
X4.5423Y-3.7008
T2
X4.4341Y-3.7008
T0
M30
